version: '3.8'

services:
  audit-log:
    build: ./
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://db:27017
      - MONGO_DB=your_database_name
      - MONGO_COLLECTION=your_collection_name

  db:
    restart: always
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data:
