version: '3.8'

services:
  audit-log:
    build: ./
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy

  db:
    restart: always
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
      
volumes:
  mongodb_data:
